version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/moia-dev/aws-apigateway-exporter
    steps:
      - checkout
      - run: make lint

workflows:
  version: 2
  ci:
    jobs:
      - lint

