version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/moia-dev/aws-apigateway-exporter
    steps:
      - checkout
      - run: make lint
      - run: make build-linux

workflows:
  version: 2
  ci:
    jobs:
      - build
